import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { checkDeviceUserAgent } from "@/lib/check-device.server";
import { DeviceContextProvider } from "@/context/device-context";
import { AuthProvider } from "@/components/providers/auth-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isDesktop: isDesktopServer, isAndroid } =
    await checkDeviceUserAgent();
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        <DeviceContextProvider
          isDesktop={isDesktopServer}
          isAndroid={isAndroid}
        >
          <AuthProvider>
            {children}
            <Toaster position="bottom-right" />
          </AuthProvider>
        </DeviceContextProvider>
      </body>
    </html>
  );
}
