import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { checkDeviceUserAgent } from "@/lib/check-device.server";
import { DeviceContextProvider } from "@/context/device-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { isDesktop: isDesktopServer, isAndroid } =
    await checkDeviceUserAgent();
  return (
    <html lang="en">
      <body
        className={`${inter.className} antialiased`}
        suppressHydrationWarning
      >
        <DeviceContextProvider
          isDesktop={isDesktopServer}
          isAndroid={isAndroid}
        >
          <SessionProvider>
            {children}
            <Toaster position="bottom-right" />
          </SessionProvider>
        </DeviceContextProvider>
      </body>
    </html>
  );
}
